import { ReactNode } from "react";
import Navbar from "@/components/shared/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
